seed: 42
weight_dtype: fp16
stage_init: True

modules:
  vae: "${oc.env:VAE_PATH}"
  unet_2d: "${oc.env:UNET_2D_PATH}"
  scheduler: "${oc.env:SCHEDULER_PATH}"
  apperance_encoder: "${oc.env:UNET_2D_PATH}" # Initialized from base UNet
  condition_encoder: 
  empty_text_emb: "${oc.env:EMPTY_TEXT_EMB_PATH}"
  unet:
  unet_additional_kwargs:
    unet_use_cross_frame_attention: false
    unet_use_temporal_attention: false
    use_motion_module: false

grad:
  vae: False
  unet_2d: False
  appearance_encoder: True
  text_encoder: False
  condition_encoder: True

gradient_checkpointing: False

solver:
  max_train_steps: 30000
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer:
    use_8bit_adam: False
    learning_rate: 1e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 1.0e-2
    adam_epsilon: 1.0e-8
  lr_scheduler:
    name: "constant"
    lr_warmup_steps: 100

dataset:
  frame_size: [272,224]
  frame_scale: [ 1.0, 1.0 ]
  frame_ratio: [ 0.9, 1.0 ]
  roots:
    - "${oc.env:DATASET_ROOT}"
  sk_roots:
    - "${oc.env:DATASET_ROOT}"
  hamer_roots:
    - "${oc.env:DATASET_ROOT}"
  meta_paths:
    - "${oc.env:TRAIN_META}"
  sample_rate: 2
  num_frames: 4
  ref_margin: 5
  uncond_ratio: 1
  mask_ratio: 0
  mask_thershold: 0.85
  skip_ratio: 0
  sk_mask_ratio: 0.1
  hamer_mask_ratio: 0.1
  both_mask_ratio: 0

dataloader:
  batch_size: 32
  num_workers: 8

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  steps_offset: 1
  clip_sample: false

resume_from_checkpoint: 
checkpointing_steps: 2000
valid_steps: 500
max_ckpt: 1
max_model: 1

enable_zero_snr: False
noise_offset: 0
clip_skip: 1
snr_gamma: 0

max_visible_frames: 6
max_sin_pe_len: 1000

validation_data:
  meta_paths:
    - "${oc.env:VAL_META}"
  prompt: ""
  num_inference_steps: 20
  guidance_scale: 3.5
